content:
  - name: docs
    label: Documentation
    type: collection
    path: docs/src/docs
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
    
  