media: docs/media
content:
  - name: docs
    label: Documentation
    type: collection
    path: docs
    filename: "{primary}.md"
    view:
      fields: [ title, nav_order ]
      primary: title
      sort: [ nav_order, title ]
      default:
        sort: nav_order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: nav_order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }