media:
  input: src/media
  output: /media
content:
  - name: docs
    label: Documentation
    type: collection
    path: src/docs
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - name: features
        label: Features
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: icon, label: Icon, type: string }
              - { name: pro, label: Pro, type: boolean }
              - { name: soon, label: Soon, type: boolean }
      - name: faq
        label: FAQ
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: question, label: Question, type: string }
              - { name: answer, label: Answer, type: text, options: { rows: 5 } }
      - { name: body, label: Body, type: code, options: { format: html} }